import { withAppBuildGradle } from "expo/config-plugins";
import type { ConfigPlugin } from "expo/config-plugins";

/**
 * Injects the release signing config into `android/app/build.gradle`.
 *
 * `android/` is gitignored and regenerated by `expo prebuild`, so signing
 * cannot be patched into that file directly — it has to be re-injected on
 * every prebuild.
 */

const DEBUG_SIGNING_CONFIG = `        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }`;

const RELEASE_SIGNING_CONFIG = `
        release {
            storeFile file(System.getenv("ANDROID_KEYSTORE_PATH") ?: "release.keystore")
            storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
            keyAlias System.getenv("ANDROID_KEY_ALIAS")
            keyPassword System.getenv("ANDROID_KEY_PASSWORD")
        }`;

/**
 * The text `signingConfig signingConfigs.debug` appears twice in
 * build.gradle — once in `buildTypes.debug`, once in `buildTypes.release`.
 * The line after it is the only thing that tells them apart, so the anchor
 * spans two lines.
 */
const RELEASE_BUILD_TYPE_ANCHOR = `            signingConfig signingConfigs.debug
            def enableShrinkResources`;

const RELEASE_BUILD_TYPE_REPLACEMENT = `            signingConfig System.getenv("ANDROID_KEYSTORE_PASSWORD") ? signingConfigs.release : signingConfigs.debug
            def enableShrinkResources`;

const TEMPLATE_DRIFT_HINT =
  "The Expo template has probably changed. Update the anchors in configs/signing.config.ts — " +
  "do not let this transform become a no-op, because the result is a debug-signed APK that looks like a release.";

export function addReleaseSigningConfig(contents: string): string {
  // Already transformed (e.g. prebuild ran twice without --clean).
  if (contents.includes("signingConfigs.release")) {
    return contents;
  }

  if (!contents.includes(DEBUG_SIGNING_CONFIG)) {
    throw new Error(
      `signingConfigs.debug block not found in app/build.gradle. ${TEMPLATE_DRIFT_HINT}`,
    );
  }

  if (!contents.includes(RELEASE_BUILD_TYPE_ANCHOR)) {
    throw new Error(
      `Signing line in buildTypes.release not found in app/build.gradle. ${TEMPLATE_DRIFT_HINT}`,
    );
  }

  return contents
    .replace(
      DEBUG_SIGNING_CONFIG,
      DEBUG_SIGNING_CONFIG + RELEASE_SIGNING_CONFIG,
    )
    .replace(RELEASE_BUILD_TYPE_ANCHOR, RELEASE_BUILD_TYPE_REPLACEMENT);
}

export const withReleaseSigning: ConfigPlugin = (config) =>
  withAppBuildGradle(config, (gradleConfig) => {
    if (gradleConfig.modResults.language !== "groovy") {
      throw new Error(
        `app/build.gradle uses ${gradleConfig.modResults.language}, not groovy. ${TEMPLATE_DRIFT_HINT}`,
      );
    }

    gradleConfig.modResults.contents = addReleaseSigningConfig(
      gradleConfig.modResults.contents,
    );

    return gradleConfig;
  });
